# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' GibbsSampler for Bivariate Normal Data with known Covariance Matrix
#' 
#'
#' @param X n x 2 matrix  of sample data
#' @param Sigma 2x2 known covariance matrix
#' @param iter_max integer maximum number of iterations
#' @param warm_up integer number of iterations to warm_up the chain
#' @param verbose boolean that indicates whether to print progress messages
#' @param seed random number generator seed
#'
GibbsSampler <- function(X, Sigma, iter_max, warm_up, verbose, seed) {
    .Call(`_dragonsfirstRcpp_GibbsSampler`, X, Sigma, iter_max, warm_up, verbose, seed)
}

